name: FFMPEG

on:
  push:
    branches: [gh-pages]

jobs:
  build:
    name: build hls
    # runs-on: ubuntu-20.04
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install FFMPEG
        # run: sudo apt-get update && sudo apt-get install ffmpeg
        run: brew install ffmpeg
      - name: Remove old sample
        run: rm rf sample
      - name: Build
        run: sh hls.sh sample.mp4 sample
      - name: Make Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "[auto] Generate HLS File"
          git push
