name: FFMPEG

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Merge from master
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch --all
          git checkout gh-pages
          git merge master --no-ff

      - name: Install FFMPEG
        run: sudo apt-get update && sudo apt-get install ffmpeg curl

      - name: Download sample video
        run: |
          curl -o movie.mp4 http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4
          ffmpeg -i movie.mp4 -ss 00:00:00 -t 00:00:58 -async 1 sample.mp4

      - name: Remove old sample
        run: rm -rf sample

      - name: Build
        run: |
          sh hls.sh sample.mp4 sample
          rm movie.mp4 sample.mp4

      - name: Make Commit
        run: |
          git add .
          git commit -m "[auto] Generate HLS File"
          git push
