name: FFMPEG

on:
  push:
    branches: [master]

jobs:
  build:
    name: build hls
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Install FFMPEG
        run: sudo apt-get update && sudo apt-get install ffmpeg

      - name: Merge from master
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git merge master

      - name: Remove old sample
        run: rm -rf sample

      - name: Build
        run: sh hls.sh sample.mp4 sample

      - name: Make Commit
        run: |
          git add .
          git commit -m "[auto] Generate HLS File"
          git push
